# Generated by Django 4.1 on 2023-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="smsCode",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
