# Generated by Django 4.1 on 2023-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Galaxies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "galaxy_name",
                    models.CharField(max_length=50, verbose_name="galaxy_name"),
                ),
                (
                    "galaxy_num",
                    models.CharField(max_length=50, verbose_name="galaxy_num"),
                ),
                ("raj", models.FloatField(default=0, verbose_name="raj")),
                ("decj", models.FloatField(default=0, verbose_name="decj")),
                ("created_time", models.DateTimeField(verbose_name="Createtime")),
                (
                    "classify_num",
                    models.IntegerField(default=0, verbose_name="classified_num"),
                ),
                (
                    "hope_classify_num",
                    models.IntegerField(default=5, verbose_name="hope_classify_num"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserClassifyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classify_id",
                    models.CharField(max_length=64, verbose_name="classify_id"),
                ),
                ("username", models.CharField(max_length=32)),
                ("galaxy_name", models.CharField(max_length=32)),
                ("created_time", models.DateTimeField(verbose_name="Createtime")),
                (
                    "type1",
                    models.IntegerField(
                        choices=[
                            (0, "Elliptical"),
                            (1, "Spiral"),
                            (2, "Disk"),
                            (3, "Stars"),
                            (4, "Others"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="type1",
                    ),
                ),
                ("notation", models.TextField(max_length=200)),
            ],
        ),
    ]
