# Generated by Django 4.1 on 2023-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galaxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userclassifyrecord",
            name="galaxy_name",
            field=models.CharField(max_length=32, verbose_name="galaxy_name"),
        ),
        migrations.AlterField(
            model_name="userclassifyrecord",
            name="username",
            field=models.CharField(max_length=32, verbose_name="username"),
        ),
    ]
