# Generated by Django 4.1 on 2023-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galaxy", "0004_alter_galaxies_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galaxies",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="decj"),
        ),
    ]
